GET localhost:8080/api/grocery-lists

###
POST localhost:8080/api/grocery-lists HTTP/1.1
Content-Type: application/json

{
  "name": "test list",
  "createdAt": "2021-05-16",
  "products": [
    {
      "product": "pepsi",
      "quantity": 3
    }
  ]
}

###

DELETE localhost:8080/api/grocery-lists/1

###

DELETE localhost:8080/api/grocery-lists/delete-by-name/every day shopping

###

POST localhost:8080/api/grocery-lists/1/add-item
Content-Type: application/json

{
  "product": "maslo",
  "quantity": 2
}

###

DELETE localhost:8080/api/grocery-lists/1/remove-item/2
